name: music_player
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  assets_audio_player: ^3.0.6
  audioplayers: ^4.1.0
  cupertino_icons: ^1.0.2
  floating_navbar: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  heroicons: ^0.8.0
  iconsax: ^0.0.8

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    #images
    - assets/images/darkside.jpg
    - assets/images/itsmylife.jpg
    - assets/images/loseurself.jpg
    - assets/images/mocking_bird.jpg
    - assets/images/safari.jpg
    - assets/images/takeaway.jpg
    - assets/images/numb.jpg
    - assets/images/end.jpg
    - assets/images/baby.jpg
    - assets/images/break.jpg
    - assets/images/thought.jpg

    #audios
    - assets/audios/Its_My_Life.mp3
    - assets/audios/The_Dark_Side.mp3
    - assets/audios/Thought_Contagion.mp3
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
